permalink: /posts/:title
name: Martin Qian
url: http://mackuntu.com
description: Blog on everything
twitter: martin_qian
github: mackuntu
gravatar_url: http://www.gravatar.com/avatar/a04824a3dfa209764fd7a64fdcae4896.png
