---
title: MartinNotes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: MartinNotes
description: a blog of Martin Qian.
logo: assets/images/logo.png
favicon: favicon.ico
baseurl: 
google_analytics: G-MK0NRFNRDN
disqus: mackuntu
include:
- _pages
permalink: "/:title/"
authors:
  martin:
    name: Martin
    display_name: Martin
    gravatar: a04824a3dfa209764fd7a64fdcae4896
    email: mackuntu@gmail.com
    web: https://www.mackuntu.com
    twitter: https://twitter.com/martin_qian
    description: I'm a tech leader, passionate about building great products to address
      people's needs. I write occasional blogs about pivotal moments in my career.
      I try to collate profound lessons learned through making a lot of mistakes.
      Also, sometimes I write about my life events.
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
paginate: 6
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: '1363087678'
lazyimages: disabled
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock

sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
  sourcemap: development
