---
title: Mackuntu.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/posts/:title"
name: Martin Qian
url: https://mackuntu.com
description: Blog on everything
twitter: martin_qian
github: mackuntu
gravatar_url: https://www.gravatar.com/avatar/a04824a3dfa209764fd7a64fdcae4896.png
theme: jekyll-theme-minimal
