---
title: Martin's shower thoughts
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/posts/:title"
name: Martin Qian
url: https://mackuntu.com
description: Profound lessons, life events, misc topics.
twitter: martin_qian
github: mackuntu
gravatar_url: https://www.gravatar.com/avatar/a04824a3dfa209764fd7a64fdcae4896.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
