backend:
  name: github
  repo: mackuntu/mackuntu.github.io
  branch: master

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list", default: ["uncategorized"]}
      - {label: "Tags", name: "tags", widget: "list", default: ["new"]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Author", name: "author", widget: "string", default: "martin"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Hidden", name: "hidden", widget: "boolean", default: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"} 